Add Chest entity
chasinglogic/workshop-game pull request #1
Opened 2021-03-05 16:31 UTC by 2Steaks

2021-03-05 16:37 UTC, chasinglogic requested changes
If you use `black` on that file it will fix it.

2021-03-05 16:37 UTC, chasinglogic commented on actors/player.py
> +        self.inventory = []
This is a lint failure, you need a newline at the end of file in python.

2021-03-05 17:02 UTC, sophiedaviespatrick approved these changes
Looks good AFAICS

2021-03-06 11:03 UTC, chasinglogic approved these changes

2021-03-12 14:49 UTC, davidttest approved these changes
A couple of comments that would be nice to have

2021-03-12 14:49 UTC, davidttest commented on entities/chest.py
> +
If action is not Take all / Close, and assuming the inventory is not empty, we would want to extend the actor's inventory?

2021-03-12 14:49 UTC, davidttest commented on entities/chest.py
> +                return True
Do we want to make sure the user entered Yes or No?

2021-03-17 10:10 UTC, mikehiett-mpb approved these changes

2021-03-26 15:49 UTC, merged