This commit adds the monster fighter MVP
chasinglogic/workshop-game pull request #2
Opened 2021-03-05 16:35 UTC by mikehiett-mpb

2021-03-05 16:51 UTC, sophiedaviespatrick requested changes

2021-03-05 16:51 UTC, sophiedaviespatrick commented on entities/fights.py
> +        return ['Blow bubbles at', 'Hit', 'Kick']
(Practising git reviews) Suggest you change the first action so it is quicker for the user to type e.g. "Blow bubbles" without the "at"

2021-03-06 11:04 UTC, chasinglogic approved these changes
As long as the .idea files get removed this LGTM.

2021-03-06 11:04 UTC, chasinglogic commented on .idea/inspectionProfiles/profiles_settings.xml
> +<component name="InspectionProjectProfileManager">
Need to remove these `.idea` files

2021-03-12 11:43 UTC, 2Steaks commented on entities/fights.py
> +    def do(self, action, actor, monster):
There does not seem to be anything to handle "Kick"

2021-03-12 11:50 UTC, 2Steaks requested changes
Missing fight action handlers

2021-03-12 11:50 UTC, 2Steaks commented on entities/fights.py
> +    def do(self, action, actor, monster):
There does not seem to be anything to handle "Kick" or "Blow bubbles"

2021-03-12 11:50 UTC, 2Steaks commented on entities/monster.py
> +            return True
Might be good to have a random outcome here, where running might be unsuccessful and maybe you lose some health as a penalty before entering the fight?

2021-03-12 11:50 UTC, 2Steaks commented on entities/fights.py
> +            monster.health -= 5
Maybe randomise damage for all attacks

2021-03-12 14:59 UTC, davidttest requested changes
Should probably handle kick and blow bubbles, a couple of comments about nice to haves

2021-03-12 14:59 UTC, davidttest commented on entities/fights.py
> +            print(f'The monster hits you back for 5 health! You now have {actor.health} health left!')
Do we want the monster to hit back every time if we've hit him first?

2021-03-12 14:59 UTC, davidttest commented on entities/monster.py
> +            return True
Agree, courage should prevail! :)

2021-03-12 15:35 UTC, mikehiett-mpb commented on entities/fights.py
> +        return ['Blow bubbles at', 'Hit', 'Kick']
Done!

2021-03-12 15:43 UTC, chasinglogic commented on entities/fights.py
> +            monster.health -= 5
Not in MVP

2021-03-12 15:43 UTC, chasinglogic commented on entities/fights.py
> +            print(f'The monster hits you back for 5 health! You now have {actor.health} health left!')
Not in MVP

2021-03-12 15:44 UTC, chasinglogic commented on entities/fights.py
> +    def do(self, action, actor, monster):
These actions are always intended to miss for MVP

2021-03-12 15:44 UTC, chasinglogic commented on entities/monster.py
> +            return True
Not in MVP

2021-03-12 15:44 UTC, closed without merging