Create trap class and add trap to the starting room
chasinglogic/workshop-game pull request #3
Opened 2021-03-05 16:35 UTC by davidttest

2021-03-05 17:04 UTC, sophiedaviespatrick requested changes

2021-03-05 17:04 UTC, sophiedaviespatrick commented on scenes/dungeon.py
> -
I'm still learning git, David, so I am not sure I got this right but it looks like there may be an extra (non needed) blank link here?

2021-03-06 11:09 UTC, chasinglogic approved these changes
LGTM, one minor possible improvement

2021-03-06 11:09 UTC, chasinglogic commented on entities/trap.py
> +        random_int = random.randint(0, len(self.possible_actions) - 1)
Instead of ignoring the user input you could make the correct answer random each time by using `random.shuffle`.

Something like this ought to work:

```python
import random
from copy import deepcopy

shuffled = random.shuffle(deepcopy(self.possible_actions))
selected_action = shuffled[int(action)-1]
```

2021-03-12 11:40 UTC, 2Steaks approved these changes

2021-03-12 14:13 UTC, davidttest commented on entities/trap.py
> +        random_int = random.randint(0, len(self.possible_actions) - 1)
Shuffled return None but fixed with sample() as per https://note.nkmk.me/en/python-random-shuffle/

2021-03-12 14:20 UTC, davidttest commented on scenes/dungeon.py
> -
Hi @sophiedaviespatrick - it is best practice to leave a blank line at the end of .py files, we have a tool called flake8 that checks this for us automatically when we put PRs out, PyCharm will also indicate a PEP8 warning on the right-hand side if you take the blank line off (you can see the details of the warning when you hover over it)

2021-03-12 15:48 UTC, merged